export interface EquipmentCertificate extends Record<string, any> {
    registrationNumber: string | undefined,
    registrationCertificate: string | undefined,
    checkDate: string | undefined,
    nextCheckDate: string | undefined,
    remark: string | undefined,
    accessory:string | undefined,
}

export interface EquipmentFrom extends Record<string, any>{
    name: string | undefined,
    source: string | undefined,
    weight: string | undefined,
    status: string | undefined ,
    deptId: string | undefined ,
    masterId: string | undefined,
    enterpriseId: string | undefined,
    equipmentTypeId: string | undefined,
    equipmentSpecialTypeId: string | undefined,
    deptName: string | undefined,
    masterName: string | undefined,
    enterpriseName: string | undefined,
    equipmentTypeName: string | undefined,
    equipmentSpecialTypeName: string | undefined,
    equipmentNumber: string | undefined,
    location: string | undefined,
    specification: string | undefined,
    manufacturer: string | undefined,
    factoryNumber: string | undefined,
    dateOfProduction: string | undefined,
    remark: string | undefined,
    picture: string | undefined,
    namePlat: string | undefined,
    annualinspection: number | undefined,
    accessory: string | undefined,
    operationDate: string | undefined,
    reason: string | undefined,
    equipmentCertificateCreateReqVO: EquipmentCertificate,
}

export interface EquipmentEditFrom extends Record<string, any>{
    name: string | undefined,
    source: string | undefined,
    weight: string | undefined,
    status: string | undefined ,
    deptId: string | undefined ,
    masterId: string | undefined,
    enterpriseId: string | undefined,
    equipmentTypeId: string | undefined,
    equipmentSpecialTypeId: string | undefined,
    deptName: string | undefined,
    masterName: string | undefined,
    enterpriseName: string | undefined,
    equipmentTypeName: string | undefined,
    equipmentSpecialTypeName: string | undefined,
    equipmentNumber: string | undefined,
    location: string | undefined,
    specification: string | undefined,
    manufacturer: string | undefined,
    factoryNumber: string | undefined,
    dateOfProduction: string | undefined,
    remark: string | undefined,
    picture: string | undefined,
    namePlat: string | undefined,
    annualinspection: string | undefined,
    accessory: string | undefined,
    operationDate: string | undefined,
    reason: string | undefined,
    equipmentCertificateUpdateReqVO: EquipmentCertificate,
}

