import SnowflakeId from 'snowflake-id'; // 生成雪花id
const snowflake = new SnowflakeId({
  mid: 42,
  offset: (2019 - 1970) * 31536000 * 1000,
});
const getDfFormConfig = () => {
  return {
    labelPos: 'right',
    ruleType: 'SIMPLE',
    labelWidth: 150,
    rules: [
      {
        action: {
          with: [
            {
              type: 'SHOW',
              value: null,
              targets: [
                'field_hazardAddr',
                'field_sceneImages',
                'field_hazardDesc',
                'field_hidRiskLevelCode',
                'field_rectifyAdvise',
                'field_rectifyFlag',
                'field_rectifySituation',
                'field_rectifyImages',
                'field_rectifyPerson',
                'field_checkAcceptPerson',
                'field_verifierPerson',
                'field_rectifyTime',
              ],
            },
          ],
          other: [{ type: null, value: null, targets: [] }],
        },
        default: true,
        condition: {
          logic: true,
          children: [],
          condition: {
            field: 'field_isQualified',
            fixed: true,
            compare: 'EQ',
            fieldType: 'SelectInput',
            compareVal: ['不合格'],
          },
        },
      },
      {
        action: {
          with: [
            {
              type: 'HIDE',
              value: null,
              targets: [
                'field_hazardAddr',
                'field_sceneImages',
                'field_hazardDesc',
                'field_hidRiskLevelCode',
                'field_rectifyAdvise',
                'field_rectifyFlag',
                'field_rectifySituation',
                'field_rectifyImages',
                'field_rectifyPerson',
                'field_checkAcceptPerson',
                'field_verifierPerson',
                'field_rectifyTime',
              ],
            },
          ],
          other: [{ type: null, value: null, targets: [] }],
        },
        default: true,
        condition: {
          logic: true,
          children: [],
          condition: {
            field: 'field_isQualified',
            fixed: true,
            compare: 'NEQ',
            fieldType: 'SelectInput',
            compareVal: ['不合格'],
          },
        },
      },
      {
        action: {
          with: [
            {
              type: 'SHOW',
              value: null,
              targets: ['field_rectifySituation', 'field_rectifyImages'],
            },
          ],
          other: [{ type: null, value: null, targets: [] }],
        },
        default: true,
        condition: {
          logic: true,
          children: [],
          condition: {
            field: 'field_rectifyFlag',
            fixed: true,
            compare: 'EQ',
            fieldType: 'SelectInput',
            compareVal: ['立即整改'],
          },
        },
      },
      {
        action: {
          with: [
            {
              type: 'HIDE',
              value: null,
              targets: ['field_rectifySituation', 'field_rectifyImages'],
            },
          ],
          other: [{ type: null, value: null, targets: [] }],
        },
        default: true,
        condition: {
          logic: true,
          children: [],
          condition: {
            field: 'field_rectifyFlag',
            fixed: true,
            compare: 'NEQ',
            fieldType: 'SelectInput',
            compareVal: ['立即整改'],
          },
        },
      },
      {
        action: {
          with: [
            {
              targets: ['field_verifierPerson'],
              type: 'SHOW',
              value: null,
            },
          ],
          other: [
            {
              targets: [],
              type: null,
              value: null,
            },
          ],
        },
        default: true,
        condition: {
          logic: true,
          condition: null,
          children: [
            {
              logic: true,
              condition: {
                field: 'field_hidRiskLevelCode',
                fieldType: 'SelectInput',
                compare: 'EQ',
                fixed: true,
                compareVal: ['重大隐患'],
              },
              children: [],
            },
            {
              logic: true,
              condition: {
                field: 'field_isQualified',
                fieldType: 'SelectInput',
                compare: 'EQ',
                fixed: true,
                compareVal: ['不合格'],
              },
              children: [],
            },
          ],
        },
      },
      {
        action: {
          with: [
            {
              targets: ['field_verifierPerson'],
              type: 'HIDE',
              value: null,
            },
          ],
          other: [
            {
              targets: [],
              type: null,
              value: null,
            },
          ],
        },
        default: true,
        condition: {
          logic: true,
          condition: null,
          children: [
            {
              logic: true,
              condition: {
                field: 'field_hidRiskLevelCode',
                fieldType: 'SelectInput',
                compare: 'NEQ',
                fixed: true,
                compareVal: ['重大隐患'],
              },
              children: [],
            },
            {
              logic: true,
              condition: {
                field: 'field_isQualified',
                fieldType: 'SelectInput',
                compare: 'EQ',
                fixed: true,
                compareVal: ['不合格'],
              },
              children: [],
            },
          ],
        },
      },
    ],
    ruleJs:
      '//formData: 表单数据  formMap: 表单字段id -> 字段json配置\r\nfunction doChange(formData, formMap){\r\n\t\r\n}',
  };
};

export const defaultFormConfig = (needDefaultId = false) => {
  return {
    formId: needDefaultId ? snowflake.generate() : '',
    logo: { icon: 'el-icon-eleme', background: '#1e90ff' },
    remark: '备注说明',
    process: {
      id: 'root',
      desc: '任何人',
      name: '发起人',
      type: 'ROOT',
      props: { formPerms: [], assignedUser: [] },
      children: {},
      parentId: null,
    },
    formData: {},
    formName: '未命名表单',
    settings: {
      sign: false,
      admin: [],
      notify: { title: '消息通知标题', types: ['APP'] },
      commiter: [],
    },
    formItems: [
      {
        id: 'field_isQualified',
        icon: 'el-icon-circleheck',
        name: 'SelectInput',
        props: {
          default: true,
          options: ['合格', '不合格', '不涉及'],
          required: true,
          expanding: true,
          enablePrint: true,
        },
        title: '是否合格',
        value: '',
        valueType: 'String',
      },
      {
        id: 'field_hazardDesc',
        icon: 'el-icon-edit',
        name: 'TextInput',
        props: {
          default: true,
          required: true,
          enableScan: false,
          enablePrint: true,
          placeholder: '请输入隐患描述',
        },
        title: '隐患描述',
        value: '',
        valueType: 'String',
      },
      {
        id: 'field_hidRiskLevelCode',
        icon: 'el-icon-edit',
        name: 'SelectInput',
        props: {
          default: true,
          options: ['一般隐患', '重大隐患'],
          required: true,
          expanding: true,
          enablePrint: true,
          placeholder: '请选择隐患级别',
        },
        title: '隐患级别',
        value: '',
        valueType: 'String',
      },
      {
        id: 'field_sceneImages',
        icon: 'el-icon-picture',
        name: 'ImageUpload',
        props: {
          default: true,
          maxSize: 5,
          required: true,
          enableZip: true,
          maxNumber: 10,
          enablePrint: true,
        },
        title: '上传现场图片',
        value: [],
        valueType: 'Array',
      },
      {
        id: 'field_rectifyPerson',
        title: '整改人',
        name: 'UserPicker',
        icon: 'el-icon-avatar',
        value: [],
        valueType: 'User',
        props: {
          default: true,
          required: true,
          enablePrint: true,
          multiple: false,
          expansion: false,
          options: [],
          valueKey: '',
          placeholder: ' ',
        },
      },
      {
        id: 'field_checkAcceptPerson',
        title: '验收人',
        name: 'UserPicker',
        icon: 'el-icon-avatar',
        value: [],
        valueType: 'User',
        props: {
          default: true,
          required: true,
          enablePrint: true,
          multiple: false,
          expansion: false,
          options: [],
          valueKey: '',
          placeholder: ' ',
        },
      },
      {
        id: 'field_verifierPerson',
        title: '复审人',
        name: 'UserPicker',
        icon: 'el-icon-avatar',
        value: [],
        valueType: 'User',
        props: {
          default: true,
          required: true,
          enablePrint: true,
          multiple: false,
          expansion: false,
          options: [],
          valueKey: '',
          placeholder: ' ',
        },
      },
      {
        id: 'field_rectifyTime',
        title: '限期整改时间',
        name: 'DateTime',
        icon: 'el-icon-calendar',
        value: '',
        valueType: 'Date',
        props: {
          default: true,
          required: true,
          enablePrint: true,
          format: 'YYYY-MM-DD HH:mm',
          valueKey: '',
          placeholder: '请选择限期整改时间',
        },
      },
      {
        id: 'field_hazardAddr',
        icon: 'el-icon-edit',
        name: 'TextInput',
        props: {
          default: true,
          enableScan: false,
          enablePrint: true,
          placeholder: '请输入隐患位置',
        },
        title: '隐患位置',
        value: '',
        valueType: 'String',
      },
      {
        id: 'field_rectifyAdvise',
        icon: 'el-icon-edit',
        name: 'TextInput',
        props: {
          default: true,
          enableScan: false,
          enablePrint: true,
          placeholder: '请输入整改建议',
        },
        title: '整改建议',
        value: '',
        valueType: 'String',
      },
      {
        id: 'field_rectifyFlag',
        icon: 'el-icon-circlecheck',
        name: 'SelectInput',
        props: {
          default: true,
          apiType: '',
          options: ['正常整改', '立即整改'],
          required: true,
          valueKey: '',
          expanding: true,
          isNeedApi: false,
          enablePrint: true,
          placeholder: '请选择整改方式',
        },
        title: '整改方式',
        value: '',
        valueType: 'String',
      },
      {
        id: 'field_rectifySituation',
        icon: 'el-icon-edit',
        name: 'TextInput',
        props: {
          default: true,
          required: true,
          valueKey: '',
          enableScan: false,
          enablePrint: true,
          placeholder: '请输入整改情况',
        },
        title: '整改情况',
        value: '',
        valueType: 'String',
      },
      {
        id: 'field_rectifyImages',
        icon: 'el-icon-picture',
        name: 'ImageUpload',
        props: {
          default: true,
          maxSize: 5,
          required: true,
          enableZip: true,
          maxNumber: 10,
          enablePrint: true,
        },
        title: '整改图片',
        value: [],
        valueType: 'Array',
      },
      {
        id: 'field_attachments',
        icon: 'el-icon-folderopened',
        name: 'FileUpload',
        props: {
          default: true,
          maxSize: 100,
          onlyRead: false,
          required: false,
          fileTypes: [],
          maxNumber: 10,
          enablePrint: true,
        },
        title: '上传附件',
        value: [],
        valueType: 'Array',
      },
    ],
    formConfig: getDfFormConfig(),
  };
};
